<?php

declare(strict_types=1);

namespace PetarSpasic\LaravelHouse\Validation;

use Illuminate\Support\Str;

/**
 * Deterministic TypeScript output: same input, same bytes.
 */
final readonly class TypeScriptRenderer
{
    public const string HEADER = '// Generated by php artisan validation:export';

    private const array RUNTIME_EXPORTS = [
        'blank', 'chars', 'dateOrder', 'different', 'field', 'isIsoDate', 'prep', 'requiredIf', 'requiredUnless',
        'requiredWith', 'requiredWithAll', 'requiredWithout', 'requiredWithoutAll', 'same',
    ];

    /**
     * @param  list<string>  $locales
     */
    public function runtime(array $locales, string $defaultLocale, bool $emptyToNull): string
    {
        $whitespace = $this->trimClass();
        $localeList = implode(', ', array_map($this->js(...), $locales));
        $emptyToNull = $emptyToNull ? 'true' : 'false';

        return <<<TS
            {$this->header('')}
            import type { z } from 'zod';

            export const locales = [{$localeList}] as const;
            export type Locale = (typeof locales)[number];
            export const defaultLocale: Locale = {$this->js($defaultLocale)};

            const emptyToNull = {$emptyToNull};
            const edges = /^{$whitespace}+|{$whitespace}+$/gu;
            const phpBlank = /^[ \\t\\n\\r\\0\\x0B]*$/;
            const numeric = /^[ \\t\\n\\r\\v\\f]*[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([eE][+-]?\\d+)?[ \\t\\n\\r\\v\\f]*$/;

            /** Str::trim, as TrimStrings applies it. */
            export const strTrim = (v: string): string => v.replace(edges, '');

            /** The opposite of Laravel's validateRequired. */
            export const blank = (v: unknown): boolean =>
              v == null || (typeof v === 'string' && phpBlank.test(v)) || (typeof v === 'object' && Object.keys(v).length === 0);

            /** True when Laravel runs only implicit rules on the value. */
            const skip = (v: unknown): boolean => v == null || (typeof v === 'string' && phpBlank.test(v));

            /** mb_strlen: code points, not UTF-16 units. */
            export const chars = (v: string): number => [...v].length;

            export const isIsoDate = (v: string): boolean => {
              const m = /^(\\d{4})-(\\d{2})-(\\d{2})$/.exec(v);
              if (!m) return false;
              const [y, mo, d] = [Number(m[1]), Number(m[2]) - 1, Number(m[3])];
              const date = new Date(0);
              date.setUTCFullYear(y, mo, d);
              return date.getUTCFullYear() === y && date.getUTCMonth() === mo && date.getUTCDate() === d;
            };

            /** The value Laravel validates: trimmed unless excepted, '' turned into null. */
            export const prep = (v: unknown, trim: boolean): unknown => {
              if (typeof v !== 'string') return v;
              const t = trim ? strTrim(v) : v;
              return emptyToNull && t === '' ? null : t;
            };

            /** required_if's comparison of the other field with one listed value. */
            export const matches = (o: unknown, p: string): boolean => {
              if (typeof o === 'boolean') return p === (o ? 'true' : 'false');
              if (o == null) return p.toLowerCase() === 'null';
              if (typeof o === 'number') return numeric.test(p) ? o === Number(p) : String(o) === p;
              if (typeof o === 'string') return numeric.test(o) && numeric.test(p) ? Number(o) === Number(p) : o === p;
              return false;
            };

            export const same = (a: unknown, b: unknown): boolean => skip(a) || a === b;
            export const different = (a: unknown, others: unknown[]): boolean => skip(a) || others.every((o) => o === undefined || o !== a);
            export const requiredIf = (a: unknown, o: unknown, p: string): boolean => o === undefined || !matches(o, p) || !blank(a);
            export const requiredUnless = (a: unknown, o: unknown, p: string): boolean => matches(o ?? null, p) || !blank(a);
            export const requiredWith = (a: unknown, others: unknown[]): boolean => others.every(blank) || !blank(a);
            export const requiredWithAll = (a: unknown, others: unknown[]): boolean => others.some(blank) || !blank(a);
            export const requiredWithout = (a: unknown, others: unknown[]): boolean => !others.some(blank) || !blank(a);
            export const requiredWithoutAll = (a: unknown, others: unknown[]): boolean => !others.every(blank) || !blank(a);

            export const dateOrder = (a: unknown, b: unknown, op: '<' | '>' | '<=' | '>=' | '==='): boolean => {
              if (typeof a !== 'string' || typeof b !== 'string' || !isIsoDate(a) || !isIsoDate(b)) return true;
              return op === '<' ? a < b : op === '>' ? a > b : op === '<=' ? a <= b : op === '>=' ? a >= b : a === b;
            };

            /** [test on the prepared value, message, implicit (runs on blank values, stops the field), rule group] */
            export type Step<T> = readonly [test: (v: T) => boolean, message: string, implicit?: boolean, group?: string];

            /** Laravel's per-field loop: blank values run only implicit rules; stop after an implicit failure, or any failure under bail. */
            export function field<T>(opts: { trim: boolean; bail?: boolean }, steps: readonly Step<T>[]) {
              return (v: T | null | undefined, ctx: z.RefinementCtx): void => {
                const t = prep(v, opts.trim);
                const empty = skip(t);
                const seen = new Set<string>();
                let failed: string | null | undefined = null;
                for (const [test, message, implicit, group] of steps) {
                  if (empty && !implicit) continue;
                  if (opts.bail && failed !== null && (group === undefined || group !== failed)) break;
                  if (test(t as T)) continue;
                  if (!seen.has(message)) {
                    seen.add(message);
                    ctx.addIssue({ code: 'custom', message, input: v });
                  }
                  if (implicit) break;
                  failed = group;
                }
              };
            }

            TS;
    }

    /**
     * @param  array<string, array<string, string>>  $messages  locale => key => text
     * @param  array<string, array<string, string>>  $attributes  locale => field => name
     * @param  list<string>  $notes  extra server-only comment lines
     * @param  'json'|null  $dataType  the attribute's dataType
     */
    public function form(FormSchema $schema, array $messages, array $attributes, array $notes, ?string $dataType = null): string
    {
        $comment = [];

        if (($serverOnly = [...$schema->serverOnly, ...$notes]) !== []) {
            $comment[] = '// Checked only by Laravel; failures arrive with the 422 response:';
            array_push($comment, ...array_map(fn (string $line): string => "//   {$line}", $serverOnly));
        }

        if ($schema->omitted !== []) {
            $comment[] = '// Not in the schema (the schema strips them):';
            array_push($comment, ...array_map(fn (string $line): string => "//   {$line}", $schema->omitted));
        }

        $body = $this->build($schema);
        $used = array_values(array_filter(self::RUNTIME_EXPORTS, fn (string $name): bool => preg_match('/\b'.$name.'[(<]/', $body) === 1));
        $imports = implode(', ', ['type Locale', ...$used, 'defaultLocale', 'locales']);
        $dataType = $this->js($schema->dataType($dataType));

        return implode("\n", [
            $this->header(" from {$schema->class}"),
            ...$comment,
            "import { z } from 'zod';",
            "import { {$imports} } from './_runtime';",
            '',
            'export const messages = '.$this->record($messages).' as const satisfies Record<Locale, Record<string, string>>;',
            '',
            'export const attributes = '.$this->record($attributes).' as const satisfies Record<Locale, Record<string, string>>;',
            '',
            "export const dataType: 'form' | 'json' = {$dataType};",
            '',
            $body,
            '',
            'const schemas = Object.fromEntries(locales.map((l) => [l, build(messages[l])])) as Record<Locale, ReturnType<typeof build>>;',
            '',
            '/** One instance per locale, built once: superforms caches adapters by schema identity. */',
            'export function schema(locale: Locale = defaultLocale) {',
            '  return schemas[locale];',
            '}',
            '',
            'export type Input = z.input<ReturnType<typeof build>>;',
            '',
        ]);
    }

    private function header(string $from): string
    {
        return self::HEADER."{$from}. Do not edit.";
    }

    private function build(FormSchema $schema): string
    {
        $out = "const build = (m: (typeof messages)[Locale]) =>\n  z\n    .object(".$this->object($schema->root, 2).')';

        foreach ($schema->checks as $check) {
            $path = implode(', ', array_map($this->js(...), $check['path']));
            $out .= "\n    .refine((d) => {$check['test']}, { path: [{$path}], error: m[{$this->js($check['key'])}], when: () => true })";
        }

        return $out.';';
    }

    private function object(Node $node, int $depth): string
    {
        $pad = str_repeat('  ', $depth);
        $lines = [];

        foreach ($node->children as $key => $child) {
            if (! $child->omitted) {
                $lines[] = $pad.'  '.$this->key((string) $key).': '.$this->node($child, $depth + 1).',';
            }
        }

        return $lines === [] ? '{}' : "{\n".implode("\n", $lines)."\n{$pad}}";
    }

    private function node(Node $node, int $depth): string
    {
        $error = $this->error($node);

        $out = match ($node->type) {
            'string' => "z.string({$error})",
            'number' => "z.number({$error})",
            'boolean' => "z.boolean({$error})",
            'array' => ($node->map ? 'z.record(z.string(), ' : 'z.array(').($node->element === null ? 'z.unknown()' : $this->node($node->element, $depth)).($error === '' ? '' : ", {$error}").')',
            default => 'z.object('.$this->object($node, $depth).')',
        };

        if ($node->nullable) {
            $out .= '.nullable()';
        }

        if ($node->steps !== []) {
            $type = ['string' => 'string', 'number' => 'number', 'boolean' => 'boolean', 'array' => $node->map ? null : 'unknown[]'][$node->type] ?? 'Record<string, unknown>';
            $options = '{ trim: '.($node->trim ? 'true' : 'false').($node->bail ? ', bail: true' : '').' }';
            $pad = str_repeat('  ', $depth + 1);
            $steps = array_map(fn (array $step): string => $pad.'  ['.implode(', ', array_filter([
                "(v) => {$step['test']}",
                'm['.$this->js($step['key']).']',
                $step['implicit'] || $step['group'] !== null ? ($step['implicit'] ? 'true' : 'false') : null,
                $step['group'] === null ? null : $this->js($step['group']),
            ], fn (?string $part): bool => $part !== null)).'],', $node->steps);
            $out .= ".superRefine(\n{$pad}field<{$type}>({$options}, [\n".implode("\n", $steps)."\n{$pad}]),\n".str_repeat('  ', $depth).')';
        }

        if ($node->optional) {
            $out .= '.optional()';
        }

        return $out;
    }

    private function error(Node $node): string
    {
        $blank = $node->blankKey ?? $node->typeKey;
        $type = $node->typeKey ?? $node->blankKey;

        return match (true) {
            $blank === null => '',
            $blank === $type => '{ error: m['.$this->js($blank).'] }',
            default => '{ error: (i) => (blank(i.input) ? m['.$this->js($blank).'] : m['.$this->js($type).']) }',
        };
    }

    /**
     * @param  array<string, array<string, string>>  $record
     */
    private function record(array $record): string
    {
        $out = "{\n";

        foreach ($record as $locale => $entries) {
            $out .= '  '.$this->key((string) $locale).': {'.($entries === [] ? '' : "\n");

            foreach ($entries as $key => $text) {
                $out .= '    '.$this->js((string) $key).': '.$this->js($text).",\n";
            }

            $out .= ($entries === [] ? '' : '  ')."},\n";
        }

        return $out.'}';
    }

    private function key(string $key): string
    {
        return preg_match('/^[A-Za-z_$][A-Za-z0-9_$]*$/', $key) === 1 ? $key : $this->js($key);
    }

    private function js(mixed $value): string
    {
        return json_encode($value, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }

    /** The characters Str::trim strips, as a JS character class. */
    private function trimClass(): string
    {
        $pattern = '~^[\s'.Str::INVISIBLE_CHARACTERS." \n\r\t\v\0".']$~u';
        $points = [];

        for ($cp = 0; $cp <= 0x3100; $cp++) {
            if (($cp < 0xD800 || $cp > 0xDFFF) && preg_match($pattern, mb_chr($cp, 'UTF-8')) === 1) {
                $points[] = $cp;
            }
        }

        preg_match_all('/\\\\x\{([0-9A-Fa-f]+)\}/', Str::INVISIBLE_CHARACTERS, $m);
        $points = array_values(array_unique([...$points, ...array_map(hexdec(...), $m[1])]));
        sort($points);

        $ranges = [];

        foreach ($points as $cp) {
            $last = array_key_last($ranges);

            if ($last !== null && $ranges[$last][1] === $cp - 1) {
                $ranges[$last][1] = $cp;
            } else {
                $ranges[] = [$cp, $cp];
            }
        }

        $u = fn (int $cp): string => sprintf('\u{%x}', $cp);

        return '['.implode('', array_map(fn (array $r): string => $r[0] === $r[1] ? $u($r[0]) : $u($r[0]).'-'.$u($r[1]), $ranges)).']';
    }
}
